trigger:
- main

pool:
  name: vishalAgent_75 # Changed from vmImage to name

steps:
- task: HCLAppScanOnCloudCustom@2
  inputs:
    AppSecTestService: 'EU_Prod'
    applications: '06076bc5-63d1-4f95-93a6-1c096e664645'
    scanname: 'check_static'
    scantype: 'static'
    scanloc: '$(System.DefaultWorkingDirectory)/Nested/Folder' # Updated slashes and standard code directory
    scanMethod: 'IRX'
    ScanSpeedOptions: 'balanced'
    intervention: false

    