trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC_EU'
    applications: '06076bc5-63d1-4f95-93a6-1c096e664645'
    scanname: 'Usecase5'
    scantype: 'dynamic'
    dynamicType: 'DASTAPI'
    apiScanType: 'postmanScanning'
    postmanCollectionFile: 'PostmanCollection.json'
    additionalDomainsAPIScan: 'demo.testfire.net'
    apiAuthentication: 'Record'
    networkAPIScan: 'public'